
services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: lamp_web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/apache/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    networks:
        - lamp-network
    restart: always

  db:
    image: mysql:8.0
    container_name: lamp_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - lamp-network
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
        - lamp-network

networks:
  lamp-network:

volumes:
  db_data:

